# Generated by Django 5.0.1 on 2024-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userreadsmodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadsmodel',
            name='fileID',
        ),
        migrations.RemoveField(
            model_name='userreferencemodel',
            name='fileID',
        ),
        migrations.AddField(
            model_name='userreadsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreferencemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
