# Generated by Django 5.0.1 on 2024-03-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userreadsmodel_fileid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreadsmodel',
            name='userID',
        ),
    ]
