# Generated by Django 5.0.1 on 2024-04-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userreadsmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreadsmodel',
            name='userID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
