# Generated by Django 5.0.1 on 2024-04-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_filemodel_fileaccessmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='bam_file',
            new_name='main_file',
        ),
    ]
