# Generated by Django 5.0.1 on 2024-04-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_filemodel_userfilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreferencemodel',
            name='userID',
        ),
        migrations.DeleteModel(
            name='UserReadsModel',
        ),
        migrations.DeleteModel(
            name='UserReferenceModel',
        ),
    ]
