# Generated by Django 5.0.1 on 2024-04-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_userreferencemodel_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccessmodel',
            old_name='shareID',
            new_name='accessID',
        ),
        migrations.RemoveField(
            model_name='userfilemodel',
            name='description',
        ),
    ]
