# Generated by Django 5.0.1 on 2024-04-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fileaccessmodel_accessemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilemodel',
            name='referenceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userfilemodel'),
        ),
    ]
