# Generated by Django 5.0.1 on 2024-04-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userfilemodel_referenceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genome', models.CharField(max_length=100)),
                ('fastaURL', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='userfilemodel',
            old_name='referenceID',
            new_name='reffileID',
        ),
        migrations.AddField(
            model_name='userfilemodel',
            name='reflinkID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.referencelinkmodel'),
        ),
    ]
