# Generated by Django 5.0.1 on 2024-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_referencelinkmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelinkmodel',
            name='indexURL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
