# Generated by Django 5.0.1 on 2024-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_referencelinkmodel_indexurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelinkmodel',
            name='organism',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
