# Generated by Django 5.0.1 on 2024-04-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_referencelinkmodel_organism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilemodel',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='fileaccessmodel',
            name='accessEmail',
        ),
        migrations.RemoveField(
            model_name='userfilemodel',
            name='description',
        ),
    ]
