# Generated by Django 5.0.1 on 2024-04-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_fileaccessmodel_accessid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccessmodel',
            old_name='fileID',
            new_name='file',
        ),
    ]
