# Generated by Django 5.0.1 on 2024-04-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_fileid_fileaccessmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfilemodel',
            old_name='reffileID',
            new_name='reference_file',
        ),
        migrations.RenameField(
            model_name='userfilemodel',
            old_name='reflinkID',
            new_name='reference_link',
        ),
    ]
