# Generated by Django 5.0.1 on 2024-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_reffileid_userfilemodel_reference_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilemodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
