# Generated by Django 5.0.1 on 2024-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_userfilemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
